In [3]:
from pykrx import stock
import pandas as pd

In [50]:
# KOSDAQ 종목코드 조회
stock_code = pd.DataFrame(stock.get_market_ticker_list(date="20220516", market="KOSDAQ"))

stock_code[0]

0       060310
1       054620
2       265520
3       211270
4       032790
         ...
1553    024060
1554    010240
1555    189980
1556    037440
1557    238490
Name: 0, Length: 1558, dtype: object

In [52]:
df = stock.get_market_ohlcv("20220510", "20220516", '238490')
df

              시가    고가    저가    종가    거래량
날짜
2022-05-10  8300  8420  8050  8320  13654
2022-05-11  8220  8380  8220  8330  10863
2022-05-12  8320  8320  8000  8000  16658
2022-05-13  8080  8150  8000  8150  11749
2022-05-16  8090  8200  7990  8020  10975

In [46]:
# 일자별 OHLCV 조회(상한가 데이터 조회)

for i in stock_code[0]:
    df = stock.get_market_ohlcv("20220510", "20220516", i)
    df['코드'] = ['%s' %i]

ValueError: Length of values (1) does not match length of index (5)

In [19]:
df['h/c'] = (df['고가'] - df['종가'].shift(1))/ df['종가'].shift(1)

In [20]:
daily_high = df['h/c'] >= 0.25:

              시가    고가    저가    종가    거래량       h/c
날짜
2022-05-02  9030  9030  8940  9010   5596       NaN
2022-05-03  9070  9070  8970  8990   9339  0.006659
2022-05-04  8950  8960  8800  8810  10067 -0.003337
2022-05-06  8790  9200  8530  8660  18638  0.044268
2022-05-09  8570  8690  8420  8430  14213  0.003464
2022-05-10  8300  8420  8050  8320  13654 -0.001186
2022-05-11  8220  8380  8220  8330  10863  0.007212
2022-05-12  8320  8320  8000  8000  16658 -0.001200
2022-05-13  8080  8150  8000  8150  11749  0.018750
2022-05-16  8090  8200  7990  8020  10975  0.006135

In [27]:
df = stock.get_market_ohlcv("20160401", "20160404", '036480')
df['h/c'] = (df['고가'] - df['종가'].shift(1))/ df['종가'].shift(1)
df

               시가     고가     저가     종가     거래량       h/c
날짜
2016-04-01  11119  14632  11119  13812  114942       NaN
2016-04-04  14772  17954  14442  17955  117668  0.299884